# Generated by Django 5.0.4 on 2025-06-26 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
        ("permissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="org_role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="permissions.role",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Admin"),
                    ("ORG_ADMIN", "Organization Admin"),
                    ("USER", "User"),
                ],
                default="USER",
                max_length=50,
            ),
        ),
    ]
