# Generated by Django 5.2.2 on 2025-07-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="contact_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
