# Generated by Django 5.2.2 on 2025-06-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super Admin"),
                    ("ORG_ADMIN", "Organization Admin"),
                    ("USER", "User"),
                    ("VERIFIER", "Verifier"),
                    ("SALESPERSON", "Salesperson"),
                    ("WORKER", "Worker"),
                    ("TEAM_LEAD", "Team Lead"),
                ],
                default="USER",
                max_length=50,
            ),
        ),
    ]
