# Generated by Django 5.2.2 on 2025-06-27 05:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_alter_user_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
