# Generated by Django 4.2.23 on 2025-07-15 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
    ]
