# Generated by Django 5.2.2 on 2025-06-29 06:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "authentication",
            "0003_alter_user_managers_rename_org_role_user_role_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="team",
        ),
    ]
