# Generated by Django 5.2.2 on 2025-07-15 03:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar",
        ),
    ]
