# Generated by Django 5.2.2 on 2025-07-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_add_role_and_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sales_target",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
