# Generated by Django 5.2.2 on 2025-07-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_alter_user_contact_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="sales_target",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=15, null=True
            ),
        ),
    ]
