# Generated by Django 5.2.2 on 2025-08-05 09:46

import deals.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0004_alter_user_organization_alter_user_role'),
        ('organization', '0001_initial'),
        ('permissions', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', validators=[deals.validators.validate_file_security]),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'status'], name='authenticat_organiz_cb949f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='authenticat_status_35d44c_idx'),
        ),
    ]
