# Generated by Django 5.2.2 on 2025-07-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_remove_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="login_count",
            field=models.IntegerField(default=0),
        ),
    ]
