# Generated by Django 5.2.2 on 2025-07-01 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_remove_user_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sales_target",
            field=models.DecimalField(decimal_places=2, default=15000.0, max_digits=15),
        ),
        migrations.AddField(
            model_name="user",
            name="streak",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
