# Generated by Django 5.2.2 on 2025-07-06 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_password_change_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text="User's address", null=True),
        ),
        migrations.CreateModel(
            name='UserNotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desktop_notifications', models.BooleanField(default=True, help_text='Enable desktop notifications')),
                ('unread_badge', models.BooleanField(default=False, help_text='Show unread notification badge')),
                ('push_timeout', models.CharField(choices=[('select', 'Select the Option'), ('15', '15 Minutes'), ('30', '30 Minutes'), ('60', '1 Hour'), ('1days', '1 Day'), ('7days', '7 Days'), ('never', 'Never')], default='select', help_text='Push notification timeout', max_length=20)),
                ('communication_emails', models.BooleanField(default=True, help_text='Receive communication emails')),
                ('announcements_updates', models.BooleanField(default=False, help_text='Receive announcements and updates')),
                ('notification_sounds', models.BooleanField(default=True, help_text='Enable notification sounds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Notification Preferences',
                'verbose_name_plural': 'User Notification Preferences',
            },
        ),
    ]
