# Generated by Django 5.2.2 on 2025-08-13 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_add_secure_user_session'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='secureusersession',
            new_name='authenticat_user_id_1770dc_idx',
            old_name='authenticat_user_id_b8e8c5_idx',
        ),
        migrations.RenameIndex(
            model_name='secureusersession',
            new_name='authenticat_user_id_de75bd_idx',
            old_name='authenticat_user_id_0c7b8a_idx',
        ),
        migrations.RenameIndex(
            model_name='secureusersession',
            new_name='authenticat_session_1546f4_idx',
            old_name='authenticat_session_4b5c6d_idx',
        ),
        migrations.RenameIndex(
            model_name='secureusersession',
            new_name='authenticat_jwt_tok_d180a6_idx',
            old_name='authenticat_jwt_tok_7e8f9a_idx',
        ),
        migrations.RenameIndex(
            model_name='secureusersession',
            new_name='authenticat_ip_addr_2db122_idx',
            old_name='authenticat_ip_addr_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='secureusersession',
            new_name='authenticat_user_ag_276a05_idx',
            old_name='authenticat_user_ag_4d5e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='secureusersession',
            new_name='authenticat_session_15b13f_idx',
            old_name='authenticat_session_7g8h9i_idx',
        ),
        migrations.RenameIndex(
            model_name='secureusersession',
            new_name='authenticat_is_susp_2b102a_idx',
            old_name='authenticat_is_susp_0j1k2l_idx',
        ),
        migrations.RenameIndex(
            model_name='secureusersession',
            new_name='authenticat_expires_cf1d4a_idx',
            old_name='authenticat_expires_3m4n5o_idx',
        ),
        migrations.RenameIndex(
            model_name='secureusersession',
            new_name='authenticat_last_ac_5db268_idx',
            old_name='authenticat_last_ac_6p7q8r_idx',
        ),
        migrations.RenameIndex(
            model_name='secureusersession',
            new_name='authenticat_is_acti_23402a_idx',
            old_name='authenticat_is_acti_9s0t1u_idx',
        ),
        migrations.RenameIndex(
            model_name='secureusersession',
            new_name='authenticat_login_m_ae8650_idx',
            old_name='authenticat_login_m_2v3w4x_idx',
        ),
        migrations.RenameIndex(
            model_name='secureusersession',
            new_name='authenticat_device__3a7a01_idx',
            old_name='authenticat_device__5y6z7a_idx',
        ),
        migrations.RenameIndex(
            model_name='secureusersession',
            new_name='authenticat_browser_79b4fe_idx',
            old_name='authenticat_browser_8b9c0d_idx',
        ),
    ]
