# Generated by Django 5.2.2 on 2025-08-13 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_add_secure_user_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=10)),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('purpose', models.CharField(choices=[('login', 'Login Verification'), ('password_reset', 'Password Reset'), ('email_verification', 'Email Verification'), ('admin_action', 'Admin Action Verification'), ('sensitive_operation', 'Sensitive Operation')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('is_locked', models.BooleanField(db_index=True, default=False)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('delivery_method', models.CharField(default='email', max_length=20)),
                ('delivery_status', models.CharField(default='pending', max_length=20)),
                ('delivery_attempts', models.IntegerField(default=0)),
                ('last_delivery_attempt', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Token',
                'verbose_name_plural': 'OTP Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'is_used'], name='authenticat_user_id_aac9ae_idx'), models.Index(fields=['token_hash'], name='authenticat_token_h_d27156_idx'), models.Index(fields=['expires_at'], name='authenticat_expires_8a3add_idx'), models.Index(fields=['user', 'created_at'], name='authenticat_user_id_64e106_idx'), models.Index(fields=['ip_address', 'created_at'], name='authenticat_ip_addr_f72693_idx'), models.Index(fields=['is_locked', 'locked_until'], name='authenticat_is_lock_f4a0b4_idx'), models.Index(fields=['user', 'purpose', 'created_at'], name='authenticat_user_id_6f160c_idx'), models.Index(fields=['attempts', 'max_attempts'], name='authenticat_attempt_4c02f2_idx')],
            },
        ),
    ]
