# Generated by Django 5.2.2 on 2025-07-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="sales_goal",
            field=models.DecimalField(
                decimal_places=2, default=100000.0, max_digits=15
            ),
        ),
    ]
