# Generated by Django 5.2.2 on 2025-07-09 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_client_notifications', models.BooleanField(default=True)),
                ('enable_deal_notifications', models.BooleanField(default=True)),
                ('enable_user_management_notifications', models.BooleanField(default=True)),
                ('enable_team_notifications', models.BooleanField(default=True)),
                ('enable_project_notifications', models.BooleanField(default=True)),
                ('enable_commission_notifications', models.BooleanField(default=True)),
                ('enable_system_notifications', models.BooleanField(default=True)),
                ('min_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='low', max_length=20)),
                ('auto_mark_read_days', models.PositiveIntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('client_created', 'New Client Created'), ('deal_created', 'New Deal Created'), ('deal_updated', 'Deal Updated'), ('deal_status_changed', 'Deal Status Changed'), ('user_created', 'New User Created'), ('role_created', 'New Role Created'), ('team_created', 'New Team Created'), ('project_created', 'New Project Created'), ('commission_created', 'New Commission Created'), ('payment_received', 'Payment Received'), ('new_organization', 'New Organization Created'), ('system_alert', 'System Alert')], max_length=50, unique=True)),
                ('title_template', models.CharField(max_length=255)),
                ('message_template', models.TextField()),
                ('available_variables', models.TextField(blank=True, help_text='List of available template variables (JSON format)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_templates', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_notification_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('client_created', 'New Client Created'), ('deal_created', 'New Deal Created'), ('deal_updated', 'Deal Updated'), ('deal_status_changed', 'Deal Status Changed'), ('user_created', 'New User Created'), ('role_created', 'New Role Created'), ('team_created', 'New Team Created'), ('project_created', 'New Project Created'), ('commission_created', 'New Commission Created'), ('payment_received', 'Payment Received'), ('new_organization', 'New Organization Created'), ('system_alert', 'System Alert')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('category', models.CharField(choices=[('business', 'Business Operations'), ('user_management', 'User Management'), ('system', 'System'), ('security', 'Security')], default='business', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['organization', 'created_at'], name='notificatio_organiz_b709e0_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
    ]
