# Generated by Django 5.2.2 on 2025-07-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsettings",
            name="all_notification_sounds",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="announcements_updates",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="communication_emails",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="desktop_notification",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="push_notification_timeout",
            field=models.CharField(default="select", max_length=20),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="unread_notification_badge",
            field=models.BooleanField(default=False),
        ),
    ]
