# Generated by Django 5.2.2 on 2025-07-05 14:44

import deals.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("deal_id", models.CharField(max_length=50)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("initial payment", "Initial Payment"),
                            ("partial_payment", "Partial Payment"),
                            ("full_payment", "Full Payment"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("instagram", "Instagram"),
                            ("google", "Google"),
                            ("referral", "Referral"),
                            ("others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                ("deal_value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("deal_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("wallet", "Mobile Wallet"),
                            ("bank", "Bank Transfer"),
                            ("cheque", "Cheque"),
                            ("cash", "Cash"),
                        ],
                        max_length=100,
                    ),
                ),
                ("deal_remarks", models.TextField(blank=True, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("pending", "Pending_Verification"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deals",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_deals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deals",
                        to="organization.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_deals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("organization", "deal_id")},
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to="deals.deal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField()),
                (
                    "receipt_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="receipts/",
                        validators=[deals.validators.validate_file_security],
                    ),
                ),
                ("payment_remarks", models.TextField(blank=True, null=True)),
                (
                    "received_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "cheque_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("wallet", "Mobile Wallet"),
                            ("bank", "Bank Transfer"),
                            ("cheque", "Cheque"),
                            ("cash", "Cash"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="deals.deal",
                    ),
                ),
            ],
        ),
    ]
