# Generated by Django 5.2.2 on 2025-07-10 04:06

import deals.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('organization', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('deal_id', models.CharField(max_length=50)),
                ('payment_status', models.CharField(choices=[('initial payment', 'Initial Payment'), ('partial_payment', 'Partial Payment'), ('full_payment', 'Full Payment')], max_length=50)),
                ('source_type', models.CharField(choices=[('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('google', 'Google'), ('referral', 'Referral'), ('others', 'Others')], max_length=50)),
                ('deal_name', models.CharField(default='', max_length=255)),
                ('deal_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('deal_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('wallet', 'Mobile Wallet'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('cash', 'Cash')], max_length=100)),
                ('deal_remarks', models.TextField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending_Verification'), ('rejected', 'Rejected')], default='pending', max_length=100)),
                ('client_status', models.CharField(choices=[('pending', 'Pending'), ('loyal', 'Loyal'), ('bad_debt', 'Bad Debt')], default='pending', max_length=100)),
                ('version', models.CharField(choices=[('original', 'Original'), ('edited', 'Edited')], default='original', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_deals', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='organization.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='project.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('manage_invoices', 'Can manage invoices'), ('access_verification_queue', 'Can access verification queue'), ('verify_deal_payment', 'Can verify deal payments'), ('manage_refunds', 'Can manage refunds'), ('verify_payments', 'Can verify payments')],
                'unique_together': {('organization', 'deal_id')},
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='deals.deal')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/', validators=[deals.validators.validate_file_security])),
                ('payment_remarks', models.TextField(blank=True, null=True)),
                ('received_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_type', models.CharField(choices=[('wallet', 'Mobile Wallet'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('cash', 'Cash')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='deals.deal')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inovice_file', models.FileField(blank=True, null=True, upload_to='invoices/', validators=[deals.validators.validate_file_security])),
                ('approval_date', models.DateField(auto_now_add=True)),
                ('approved_remarks', models.TextField(blank=True, null=True)),
                ('failure_remarks', models.CharField(blank=True, choices=[('insufficient_funds', 'Insufficient Funds'), ('bank_decline', 'Bank Decline'), ('technical_error', 'Technical Error'), ('cheque_bounce', 'Cheque Bounce'), ('payment_received_not_reflected', 'Payment Received but not Reflected')], max_length=50, null=True)),
                ('amount_in_invoice', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_approvals', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='deals.deal')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='deals.payment')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('invoice_status', models.CharField(default='pending', max_length=20)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='deals.deal')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='deals.payment')),
            ],
        ),
    ]
