# Generated by Django 5.2.2 on 2025-07-09 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentapproval',
            old_name='inovice_file',
            new_name='invoice_file',
        ),
    ]
