# Generated by Django 5.2.2 on 2025-07-10 08:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentapproval",
            old_name="approved_remarks",
            new_name="verifier_remarks",
        ),
    ]
