# Generated by Django 4.2.23 on 2025-07-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "permissions": [("create_deal_payment", "Can create deal payment")]
            },
        ),
    ]
