# Generated by Django 5.2.2 on 2025-07-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="client_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("loyal", "Loyal"),
                    ("bad_debt", "Bad Debt"),
                ],
                default="pending",
                max_length=100,
            ),
        ),
    ]
