# Generated by Django 5.2.2 on 2025-06-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="receipt_file",
            field=models.FileField(blank=True, null=True, upload_to="receipts/"),
        ),
    ]
