# Generated by Django 5.2.2 on 2025-07-09 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_rename_inovice_file_paymentapproval_invoice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentapproval',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='deals.paymentinvoice'),
        ),
    ]
