# Generated by Django 4.2.23 on 2025-07-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0002_alter_payment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_category",
            field=models.CharField(
                choices=[
                    ("advance", "Advance Payment"),
                    ("partial", "Partial Payment"),
                    ("final", "Final Payment"),
                ],
                default="partial",
                max_length=50,
            ),
        ),
    ]
