# Generated by Django 5.2.2 on 2025-07-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0002_deal_client_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="version",
            field=models.CharField(
                choices=[("original", "Original"), ("edited", "Edited")],
                default="original",
                max_length=10,
            ),
        ),
    ]
