# Generated by Django 5.2.2 on 2025-06-29 10:29

import deals.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0002_alter_payment_receipt_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="receipt_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="receipts/",
                validators=[deals.validators.validate_file_security],
            ),
        ),
    ]
