# Generated by Django 5.2.2 on 2025-07-21 17:04

import deals.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("deals", "0002_add_payment_count"),
        ("organization", "0001_initial"),
        ("project", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deal",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("manage_invoices", "Can manage invoices"),
                    ("access_verification_queue", "Can access verification queue"),
                    ("verify_deal_payment", "Can verify deal payments"),
                    ("manage_refunds", "Can manage refunds"),
                    ("verify_payments", "Can verify payments"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-payment_date"],
                "permissions": [("create_deal_payment", "Can create deal payment")],
            },
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="payment",
            name="receipt_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="receipts/",
                validators=[deals.models.validate_file_upload],
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["client", "created_at"], name="deals_deal_client__ea8c0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["created_by", "deal_date"], name="deals_deal_created_90cc76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["payment_status", "verification_status"],
                name="deals_deal_payment_7ed096_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["due_date"], name="deals_deal_due_dat_e9fed1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["deal_value"], name="deals_deal_deal_va_6beb9c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["deal", "payment_date"], name="deals_payme_deal_id_73d309_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["created_at"], name="deals_payme_created_bc0ad4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["received_amount"], name="deals_payme_receive_947fc7_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="deal",
            table="deals_deal",
        ),
        migrations.AlterModelTable(
            name="payment",
            table="deals_payment",
        ),
    ]
