# Generated by Django 5.2.2 on 2025-08-05 09:46

import deals.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_client_name_alter_client_email_and_more'),
        ('deals', '0003_alter_deal_options_alter_payment_options_and_more'),
        ('organization', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='deal_id',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', validators=[deals.validators.validate_file_security]),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'verification_status'], name='deals_deal_organiz_34fafc_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'payment_status'], name='deals_deal_organiz_f86d09_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['source_type'], name='deals_deal_source__b59f34_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'deal_date'], name='deals_deal_organiz_ab09d2_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'created_by'], name='deals_deal_organiz_cdfde6_idx'),
        ),
    ]
