# Generated by Django 5.2.2 on 2025-07-06 09:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_alter_client_phone_number"),
        ("deals", "0003_deal_version"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="deal",
            name="deal_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="deal",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deals",
                to="project.project",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deals",
                to="clients.client",
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="deal",
            name="deal_value",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
