# Generated by Django 5.2.2 on 2025-07-15 11:02

from django.db import migrations, models


def add_payment_count_if_not_exists(apps, schema_editor):
    """
    Add the payment_count field only if it doesn't exist in the database.
    """
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if the payment_count column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'deals_deal' 
            AND column_name = 'payment_count'
        """)
        if not cursor.fetchone():
            # Column doesn't exist, add it
            schema_editor.execute("ALTER TABLE deals_deal ADD COLUMN payment_count integer DEFAULT 0")


def reverse_add_payment_count(apps, schema_editor):
    """
    Reverse operation - remove the payment_count field if needed.
    """
    db_alias = schema_editor.connection.alias
    with schema_editor.connection.cursor() as cursor:
        # Check if the payment_count column exists
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'deals_deal' 
            AND column_name = 'payment_count'
        """)
        if cursor.fetchone():
            # Column exists, remove it
            schema_editor.execute("ALTER TABLE deals_deal DROP COLUMN payment_count")


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0003_payment_payment_category"),
    ]

    operations = [
        migrations.RunPython(
            add_payment_count_if_not_exists,
            reverse_add_payment_count,
        ),
    ]
