# Generated by Django 5.2.2 on 2025-07-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0003_alter_payment_receipt_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="deal_status",
            field=models.CharField(
                choices=[
                    ("verified", "Verified"),
                    ("pending", "Pending_Verification"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="pay_status",
            field=models.CharField(
                choices=[
                    ("initial payment", "Initial Payment"),
                    ("partial_payment", "Partial Payment"),
                    ("full_payment", "Full Payment"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="deal",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("linkedin", "LinkedIn"),
                    ("instagram", "Instagram"),
                    ("google", "Google"),
                    ("referral", "Referral"),
                    ("others", "Others"),
                ],
                max_length=50,
            ),
        ),
    ]
