# Generated by Django 5.2.2 on 2025-07-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0004_deal_currency_deal_deal_name_deal_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
