# Generated by Django 5.2.2 on 2025-07-09 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0004_payment_transaction_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paymentinvoice",
            options={"ordering": ["-invoice_date"]},
        ),
    ]
