# Generated by Django 5.2.2 on 2025-07-07 04:07

import deals.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0005_payment_created_at_payment_updated_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
        ),
        migrations.AlterField(
            model_name="payment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="PaymentApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inovice_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="invoices/",
                        validators=[deals.validators.validate_file_security],
                    ),
                ),
                ("approval_date", models.DateField(auto_now_add=True)),
                ("approved_remarks", models.TextField(blank=True, null=True)),
                (
                    "failure_remarks",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("insufficient_funds", "Insufficient Funds"),
                            ("bank_decline", "Bank Decline"),
                            ("technical_error", "Technical Error"),
                            ("cheque_bounce", "Cheque Bounce"),
                            (
                                "payment_received_not_reflected",
                                "Payment Received but not Reflected",
                            ),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "amount_in_invoice",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_approvals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="deals.deal",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approvals",
                        to="deals.payment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymentInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_id", models.CharField(max_length=50)),
                ("invoice_date", models.DateField(auto_now_add=True)),
                (
                    "invoice_status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("pending", "Pending Verification"),
                            ("rejected", "Rejected"),
                            ("refunded", "Refunded"),
                            ("bad_debt", "Bad Debt"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="deals.deal",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="deals.payment",
                    ),
                ),
            ],
        ),
    ]
