# Generated by Django 5.2.2 on 2025-07-07 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0006_alter_payment_created_at_alter_payment_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentinvoice",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentinvoice",
            name="receipt_file",
            field=models.FileField(blank=True, null=True, upload_to="receipts/"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="paymentinvoice",
            name="invoice_id",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="paymentinvoice",
            name="invoice_status",
            field=models.CharField(default="pending", max_length=20),
        ),
        migrations.AlterField(
            model_name="paymentinvoice",
            name="payment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice",
                to="deals.payment",
            ),
        ),
    ]
