# Generated by Django 5.2.2 on 2025-07-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0007_paymentinvoice_due_date_paymentinvoice_receipt_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
