# Generated by Django 5.0.4 on 2025-06-26 08:38

from django.db import migrations

PERMISSIONS_DATA = {
    "Client Management": [
        "View All Client",
        "Create Client",
        "Edit Client Details",
        "View Own Client Data",
    ],
    "Sales Management": [
        "View All Leads",
        "Assign Leads",
        "Update Deal Status",
        "View Sales Pipeline",
    ],
    "Reporting and Analysis": [
        "View Sales Report",
        "Export Data",
    ],
    "User and Role Management": [
        "View All Users",
        "Manage Roles",
        "Add or Remove Users",
        "Add or Remove Roles",
    ],
    "System Settings": [
        "Manage Permission",
        "Configure Integration",
    ],
}

def populate_permissions(apps, schema_editor):
    Permission = apps.get_model('permissions', 'Permission')
    
    for category, permissions in PERMISSIONS_DATA.items():
        for name in permissions:
            codename = name.lower().replace(" ", "_")
            Permission.objects.get_or_create(
                name=name,
                codename=codename,
                category=category
            )

class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_permissions),
    ]
