# Generated by Django 5.2.2 on 2025-07-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE permissions_role_permissions DROP CONSTRAINT IF EXISTS permissions_role_per_permission_id_cd4f2c07_fk_permissio;",
            reverse_sql="-- No reverse needed"
        ),
        migrations.RunSQL(
            "ALTER TABLE permissions_role_permissions ADD CONSTRAINT permissions_role_per_permission_id_auth_fk FOREIGN KEY (permission_id) REFERENCES auth_permission(id) DEFERRABLE INITIALLY DEFERRED;",
            reverse_sql="ALTER TABLE permissions_role_permissions DROP CONSTRAINT permissions_role_per_permission_id_auth_fk;"
        ),
    ]
