# Generated by Django 5.2.2 on 2025-06-27 05:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("permissions", "0002_populate_initial_permissions"),
        ("permissions", "0002_populate_permissions"),
    ]

    operations = []
