# Generated by Django 5.2.2 on 2025-06-29 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
        ("permissions", "0004_alter_role_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="roles",
                to="organization.organization",
            ),
        ),
    ]
