# Generated by Django 5.0.4 on 2025-06-29 14:00

from django.db import migrations

PERMISSIONS_DATA = {
    "Deal Management": [
        "Create Deal",
        "View Own Deals",
        "View All Deals",
        "Verify Deal Payment",
        "Log Deal Activity",
    ],
    "Client Management": [
        # These are repeated to ensure they exist, get_or_create handles duplicates.
        "Create Client",
        "View Own Clients",
        "View All Clients",
        "Edit Client Details",
    ],
}

def populate_new_permissions(apps, schema_editor):
    Permission = apps.get_model('permissions', 'Permission')
    
    for category, permissions in PERMISSIONS_DATA.items():
        for name in permissions:
            codename = name.lower().replace(" ", "_")
            Permission.objects.get_or_create(
                name=name,
                codename=codename,
                category=category
            )

class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_alter_role_organization'),
    ]

    operations = [
        migrations.RunPython(populate_new_permissions),
    ] 