# Generated by Django 5.2.2 on 2025-07-01 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_alter_role_organization'),
    ]

    operations = [
    ]
