# Generated by Django 5.0.4 on 2025-06-29 15:00

from django.db import migrations

def unify_user_management_permissions(apps, schema_editor):
    Permission = apps.get_model('permissions', 'Permission')
    
    # Standardize on a clear, consistent naming scheme
    permissions_to_ensure = {
        "create_user": "Create User",
        "edit_user": "Edit User",
        "view_all_users": "View All Users",
        "delete_user": "Delete User",
        "manage_roles": "Manage Roles",
    }
    
    for codename, name in permissions_to_ensure.items():
        Permission.objects.update_or_create(
            codename=codename,
            defaults={'name': name, 'category': "User and Role Management"}
        )
        
    # Remove old, inconsistently named permissions
    permissions_to_remove = [
        "add_or_remove_users",
        "add_or_remove_roles",
    ]
    Permission.objects.filter(codename__in=permissions_to_remove).delete()

def revert_unify_permissions(apps, schema_editor):
    # This revert is non-destructive, it just ensures old names are present.
    Permission = apps.get_model('permissions', 'Permission')
    Permission.objects.get_or_create(codename="add_or_remove_users", name="Add or Remove Users", category="User and Role Management")


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0006_add_deal_permissions'),
    ]

    operations = [
        migrations.RunPython(unify_user_management_permissions, revert_unify_permissions),
    ] 