# Generated by Django 5.2.2 on 2025-07-01 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0006_assign_salesperson_client_permission'),
    ]

    operations = [
    ]
