# Generated by Django 5.2.2 on 2025-06-29 16:30

from django.db import migrations

def fix_missing_permissions(apps, schema_editor):
    Permission = apps.get_model('permissions', 'Permission')
    
    # Fix missing codename for "View All Users"
    view_all_users_perm = Permission.objects.filter(name="View All Users", codename__isnull=True).first()
    if view_all_users_perm:
        view_all_users_perm.codename = "view_all_users"
        view_all_users_perm.save()
    
    # Add missing permissions referenced in code
    missing_permissions = [
        {
            'name': 'Update Deal Status',
            'codename': 'update_deal_status',
            'category': 'Deal Management'
        },
        {
            'name': 'View Own Projects',
            'codename': 'view_own_projects',
            'category': 'Project Management'
        },
        {
            'name': 'View All Projects',
            'codename': 'view_all_projects',
            'category': 'Project Management'
        },
        {
            'name': 'View Own Teams',
            'codename': 'view_own_teams',
            'category': 'Team Management'
        },
        {
            'name': 'View All Teams',
            'codename': 'view_all_teams',
            'category': 'Team Management'
        },
        {
            'name': 'Create Commission',
            'codename': 'create_commission',
            'category': 'Commission Management'
        },
        {
            'name': 'View All Commissions',
            'codename': 'view_all_commissions',
            'category': 'Commission Management'
        },
        {
            'name': 'Edit Commission',
            'codename': 'edit_commission',
            'category': 'Commission Management'
        },
        {
            'name': 'Delete Commission',
            'codename': 'delete_commission',
            'category': 'Commission Management'
        }
    ]
    
    for perm_data in missing_permissions:
        Permission.objects.get_or_create(
            codename=perm_data['codename'],
            defaults={
                'name': perm_data['name'],
                'category': perm_data['category']
            }
        )

class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0007_unify_user_permissions'),
    ]

    operations = [
        migrations.RunPython(fix_missing_permissions),
    ] 