# Generated by Django 5.2.2 on 2025-07-04 04:28

# -*- coding: utf-8 -*-
from django.db import migrations

def grant_view_user_permission(apps, schema_editor):
    """
    Grant the 'view_user' permission to all existing 'Org Admin' roles.
    """
    Role = apps.get_model('permissions', 'Role')
    Permission = apps.get_model('permissions', 'Permission')
    db_alias = schema_editor.connection.alias

    try:
        # Get the specific permission we want to assign
        view_user_perm = Permission.objects.using(db_alias).get(codename='view_user')
        
        # Find all roles named 'Org Admin' across all organizations
        org_admin_roles = Role.objects.using(db_alias).filter(name='Org Admin')
        
        for role in org_admin_roles:
            role.permissions.add(view_user_perm)
            print(f"Granted 'view_user' to 'Org Admin' in org: {role.organization}")

    except Permission.DoesNotExist:
        # This might happen in tests or if the initial permissions haven't been created yet.
        # It's safe to ignore in that case.
        print("Permission 'view_user' not found, skipping.")
        pass

def revert_view_user_permission(apps, schema_editor):
    """
    Revert the 'view_user' permission from all 'Org Admin' roles.
    """
    Role = apps.get_model('permissions', 'Role')
    Permission = apps.get_model('permissions', 'Permission')
    db_alias = schema_editor.connection.alias
    
    try:
        view_user_perm = Permission.objects.using(db_alias).get(codename='view_user')
        org_admin_roles = Role.objects.using(db_alias).filter(name='Org Admin')

        for role in org_admin_roles:
            role.permissions.remove(view_user_perm)
            print(f"Reverted 'view_user' from 'Org Admin' in org: {role.organization}")

    except Permission.DoesNotExist:
        print("Permission 'view_user' not found, skipping revert.")
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0008_add_payment_permissions'),
    ]

    operations = [
        migrations.RunPython(grant_view_user_permission, reverse_code=revert_view_user_permission),
    ]
