# Generated by Django 5.2.2 on 2025-07-10 08:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commission", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commission",
            name="converted_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
    ]
