# Generated by Django 5.0.4 on 2025-06-26 10:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commission", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commission",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="commission",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="commission",
            name="commission_percentage",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("5.00"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="converted_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="total_sales",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.RemoveField(
            model_name="commission",
            name="bonus_amount",
        ),
        migrations.RemoveField(
            model_name="commission",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="commission",
            name="exchange_rate",
        ),
        migrations.RemoveField(
            model_name="commission",
            name="penalty_amount",
        ),
        migrations.RemoveField(
            model_name="commission",
            name="total_commission",
        ),
        migrations.RemoveField(
            model_name="commission",
            name="total_receivable",
        ),
    ]
