# Generated by Django 5.2.2 on 2025-07-06 08:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commission", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commission",
            name="commission_percentage",
        ),
        migrations.RemoveField(
            model_name="commission",
            name="converted_amount",
        ),
        migrations.AddField(
            model_name="commission",
            name="bonus",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="commission_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.00"),
                max_digits=5,
                verbose_name="Commission Rate (%)",
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="currency",
            field=models.CharField(default="NPR", max_length=10),
        ),
        migrations.AddField(
            model_name="commission",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("1.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="penalty",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="total_commission",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="total_receivable",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="total_sales",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
    ]
