# Generated by Django 5.2.2 on 2025-06-27 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commission", "0002_alter_commission_options_and_more"),
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="commission",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commissions",
                to="organization.organization",
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="commissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
