# Generated by Django 5.2.2 on 2025-07-06 09:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commission", "0002_remove_commission_commission_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="commission",
            name="converted_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name="commission",
            name="bonus",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="total_sales",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=15
            ),
        ),
    ]
