# Generated by Django 5.2.2 on 2025-07-03 10:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commission", "0003_alter_commission_organization_alter_commission_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="commission",
            name="bonus",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="currency",
            field=models.CharField(
                choices=[
                    ("NEP", "Nepalese Rupee"),
                    ("AUD", "Australian Dollar"),
                    ("USD", "US Dollar"),
                ],
                default="USD",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="penalty",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5.00"),
                help_text="Commission percentage",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("1.0000"),
                help_text="Exchange rate",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="commission",
            name="total_receivable",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="commission_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="commission",
            name="converted_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
