# Generated by Django 5.2.2 on 2025-08-18 04:41

import apps.deals.atomic_operations
import apps.deals.financial_optimizer
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('currency', models.CharField(choices=[('XUA', 'ADB Unit of Account (XUA)'), ('AFN', 'Afghani (AFN)'), ('DZD', 'Algerian Dinar (DZD)'), ('ARS', 'Argentine Peso (ARS)'), ('AMD', 'Armenian Dram (AMD)'), ('AWG', 'Aruban Florin (AWG)'), ('AUD', 'Australian Dollar (AUD)'), ('AZN', 'Azerbaijan Manat (AZN)'), ('BSD', 'Bahamian Dollar (BSD)'), ('BHD', 'Bahraini Dinar (BHD)'), ('THB', 'Baht (THB)'), ('PAB', 'Balboa (PAB)'), ('BBD', 'Barbados Dollar (BBD)'), ('BYN', 'Belarusian Ruble (BYN)'), ('BZD', 'Belize Dollar (BZD)'), ('BMD', 'Bermudian Dollar (BMD)'), ('BOB', 'Boliviano (BOB)'), ('VED', 'Bolívar Soberano (VED)'), ('VES', 'Bolívar Soberano (VES)'), ('XBA', 'Bond Markets Unit European Composite Unit (EURCO) (XBA)'), ('XBB', 'Bond Markets Unit European Monetary Unit (E.M.U.-6) (XBB)'), ('XBD', 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17) (XBD)'), ('XBC', 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9) (XBC)'), ('BRL', 'Brazilian Real (BRL)'), ('BND', 'Brunei Dollar (BND)'), ('BGN', 'Bulgarian Lev (BGN)'), ('BIF', 'Burundi Franc (BIF)'), ('XOF', 'CFA Franc BCEAO (XOF)'), ('XAF', 'CFA Franc BEAC (XAF)'), ('XPF', 'CFP Franc (XPF)'), ('CVE', 'Cabo Verde Escudo (CVE)'), ('CAD', 'Canadian Dollar (CAD)'), ('KYD', 'Cayman Islands Dollar (KYD)'), ('CLP', 'Chilean Peso (CLP)'), ('XTS', 'Codes specifically reserved for testing purposes (XTS)'), ('COP', 'Colombian Peso (COP)'), ('KMF', 'Comorian Franc (KMF)'), ('CDF', 'Congolese Franc (CDF)'), ('BAM', 'Convertible Mark (BAM)'), ('NIO', 'Cordoba Oro (NIO)'), ('CRC', 'Costa Rican Colon (CRC)'), ('CUP', 'Cuban Peso (CUP)'), ('CZK', 'Czech Koruna (CZK)'), ('GMD', 'Dalasi (GMD)'), ('DKK', 'Danish Krone (DKK)'), ('MKD', 'Denar (MKD)'), ('DJF', 'Djibouti Franc (DJF)'), ('STN', 'Dobra (STN)'), ('DOP', 'Dominican Peso (DOP)'), ('VND', 'Dong (VND)'), ('XCD', 'East Caribbean Dollar (XCD)'), ('EGP', 'Egyptian Pound (EGP)'), ('SVC', 'El Salvador Colon (SVC)'), ('ETB', 'Ethiopian Birr (ETB)'), ('EUR', 'Euro (EUR)'), ('FKP', 'Falkland Islands Pound (FKP)'), ('FJD', 'Fiji Dollar (FJD)'), ('HUF', 'Forint (HUF)'), ('GHS', 'Ghana Cedi (GHS)'), ('GIP', 'Gibraltar Pound (GIP)'), ('XAU', 'Gold (XAU)'), ('HTG', 'Gourde (HTG)'), ('PYG', 'Guarani (PYG)'), ('GNF', 'Guinean Franc (GNF)'), ('GYD', 'Guyana Dollar (GYD)'), ('HKD', 'Hong Kong Dollar (HKD)'), ('UAH', 'Hryvnia (UAH)'), ('ISK', 'Iceland Krona (ISK)'), ('INR', 'Indian Rupee (INR)'), ('IRR', 'Iranian Rial (IRR)'), ('IQD', 'Iraqi Dinar (IQD)'), ('JMD', 'Jamaican Dollar (JMD)'), ('JOD', 'Jordanian Dinar (JOD)'), ('KES', 'Kenyan Shilling (KES)'), ('PGK', 'Kina (PGK)'), ('HRK', 'Kuna (HRK)'), ('KWD', 'Kuwaiti Dinar (KWD)'), ('AOA', 'Kwanza (AOA)'), ('MMK', 'Kyat (MMK)'), ('LAK', 'Lao Kip (LAK)'), ('GEL', 'Lari (GEL)'), ('LBP', 'Lebanese Pound (LBP)'), ('ALL', 'Lek (ALL)'), ('HNL', 'Lempira (HNL)'), ('SLE', 'Leone (SLE)'), ('SLL', 'Leone (SLL)'), ('LRD', 'Liberian Dollar (LRD)'), ('LYD', 'Libyan Dinar (LYD)'), ('SZL', 'Lilangeni (SZL)'), ('LSL', 'Loti (LSL)'), ('MGA', 'Malagasy Ariary (MGA)'), ('MWK', 'Malawi Kwacha (MWK)'), ('MYR', 'Malaysian Ringgit (MYR)'), ('MUR', 'Mauritius Rupee (MUR)'), ('MXN', 'Mexican Peso (MXN)'), ('MXV', 'Mexican Unidad de Inversion (UDI) (MXV)'), ('MDL', 'Moldovan Leu (MDL)'), ('MAD', 'Moroccan Dirham (MAD)'), ('MZN', 'Mozambique Metical (MZN)'), ('BOV', 'Mvdol (BOV)'), ('NGN', 'Naira (NGN)'), ('ERN', 'Nakfa (ERN)'), ('NAD', 'Namibia Dollar (NAD)'), ('NPR', 'Nepalese Rupee (NPR)'), ('ANG', 'Netherlands Antillean Guilder (ANG)'), ('ILS', 'New Israeli Sheqel (ILS)'), ('TWD', 'New Taiwan Dollar (TWD)'), ('NZD', 'New Zealand Dollar (NZD)'), ('BTN', 'Ngultrum (BTN)'), ('KPW', 'North Korean Won (KPW)'), ('NOK', 'Norwegian Krone (NOK)'), ('MRU', 'Ouguiya (MRU)'), ('PKR', 'Pakistan Rupee (PKR)'), ('XPD', 'Palladium (XPD)'), ('MOP', 'Pataca (MOP)'), ('TOP', 'Pa’anga (TOP)'), ('CUC', 'Peso Convertible (CUC)'), ('UYU', 'Peso Uruguayo (UYU)'), ('PHP', 'Philippine Peso (PHP)'), ('XPT', 'Platinum (XPT)'), ('GBP', 'Pound Sterling (GBP)'), ('BWP', 'Pula (BWP)'), ('QAR', 'Qatari Rial (QAR)'), ('GTQ', 'Quetzal (GTQ)'), ('ZAR', 'Rand (ZAR)'), ('OMR', 'Rial Omani (OMR)'), ('KHR', 'Riel (KHR)'), ('RON', 'Romanian Leu (RON)'), ('MVR', 'Rufiyaa (MVR)'), ('IDR', 'Rupiah (IDR)'), ('RUB', 'Russian Ruble (RUB)'), ('RWF', 'Rwanda Franc (RWF)'), ('XDR', 'SDR (Special Drawing Right) (XDR)'), ('SHP', 'Saint Helena Pound (SHP)'), ('SAR', 'Saudi Riyal (SAR)'), ('RSD', 'Serbian Dinar (RSD)'), ('SCR', 'Seychelles Rupee (SCR)'), ('XAG', 'Silver (XAG)'), ('SGD', 'Singapore Dollar (SGD)'), ('PEN', 'Sol (PEN)'), ('SBD', 'Solomon Islands Dollar (SBD)'), ('KGS', 'Som (KGS)'), ('SOS', 'Somali Shilling (SOS)'), ('TJS', 'Somoni (TJS)'), ('SSP', 'South Sudanese Pound (SSP)'), ('LKR', 'Sri Lanka Rupee (LKR)'), ('XSU', 'Sucre (XSU)'), ('SDG', 'Sudanese Pound (SDG)'), ('SRD', 'Surinam Dollar (SRD)'), ('SEK', 'Swedish Krona (SEK)'), ('CHF', 'Swiss Franc (CHF)'), ('SYP', 'Syrian Pound (SYP)'), ('BDT', 'Taka (BDT)'), ('WST', 'Tala (WST)'), ('TZS', 'Tanzanian Shilling (TZS)'), ('KZT', 'Tenge (KZT)'), ('XXX', 'The codes assigned for transactions where no currency is involved (XXX)'), ('TTD', 'Trinidad and Tobago Dollar (TTD)'), ('MNT', 'Tugrik (MNT)'), ('TND', 'Tunisian Dinar (TND)'), ('TRY', 'Turkish Lira (TRY)'), ('TMT', 'Turkmenistan New Manat (TMT)'), ('AED', 'UAE Dirham (AED)'), ('USN', 'US Dollar (Next day) (USN)'), ('USD', 'US Dollar (USD)'), ('UGX', 'Uganda Shilling (UGX)'), ('UYW', 'Unidad Previsional (UYW)'), ('CLF', 'Unidad de Fomento (CLF)'), ('COU', 'Unidad de Valor Real (COU)'), ('UYI', 'Uruguay Peso en Unidades Indexadas (UI) (UYI)'), ('UZS', 'Uzbekistan Sum (UZS)'), ('VUV', 'Vatu (VUV)'), ('CHE', 'WIR Euro (CHE)'), ('CHW', 'WIR Franc (CHW)'), ('KRW', 'Won (KRW)'), ('YER', 'Yemeni Rial (YER)'), ('JPY', 'Yen (JPY)'), ('CNY', 'Yuan Renminbi (CNY)'), ('ZMW', 'Zambian Kwacha (ZMW)'), ('ZWL', 'Zimbabwe Dollar (ZWL)'), ('PLN', 'Zloty (PLN)')], default='USD', max_length=3)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='Commission Rate (%)')),
                ('exchange_rate', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('penalty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_commission', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_receivable', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('converted_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lock_version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commissions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='organization.organization')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_commissions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission',
                'verbose_name_plural': 'Commissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'user'], name='commission__organiz_f156f1_idx'), models.Index(fields=['organization', 'start_date', 'end_date'], name='commission__organiz_dba360_idx'), models.Index(fields=['organization', 'created_at'], name='commission__organiz_8af37b_idx'), models.Index(fields=['user', 'start_date', 'end_date'], name='commission__user_id_afa372_idx'), models.Index(fields=['user', 'created_at'], name='commission__user_id_d93c1e_idx'), models.Index(fields=['organization', 'total_sales', 'created_at'], name='commission__organiz_3e282b_idx'), models.Index(fields=['organization', 'total_commission', 'created_at'], name='commission__organiz_430dcf_idx'), models.Index(fields=['organization', 'commission_rate'], name='commission__organiz_fa9d7a_idx'), models.Index(fields=['start_date', 'end_date'], name='commission__start_d_8cf2f0_idx'), models.Index(fields=['created_at', 'organization'], name='commission__created_ec6ce7_idx'), models.Index(fields=['updated_at', 'organization'], name='commission__updated_9ac584_idx'), models.Index(fields=['currency', 'organization'], name='commission__currenc_540a04_idx'), models.Index(fields=['exchange_rate', 'created_at'], name='commission__exchang_646239_idx'), models.Index(fields=['created_by', 'organization'], name='commission__created_3f82e2_idx'), models.Index(fields=['updated_by', 'updated_at'], name='commission__updated_6ca16d_idx')],
                'unique_together': {('user', 'organization', 'start_date', 'end_date')},
            },
            bases=(apps.deals.financial_optimizer.FinancialValidationMixin, apps.deals.atomic_operations.OptimisticLockingMixin, models.Model),
        ),
    ]
