# Generated by Django 5.2.2 on 2025-08-18 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0002_initial'),
        ('permissions', '0001_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='permissions.role'),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='team.team'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='otptoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordexpiration',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_expiration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secureusersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secure_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='investigated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigated_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'status'], name='authenticat_organiz_cb949f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='authenticat_status_35d44c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'role'], name='authenticat_organiz_c08f2c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'is_active'], name='authenticat_organiz_86d97f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'date_joined'], name='authenticat_organiz_c42a61_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'last_login'], name='authenticat_organiz_04db03_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='authenticat_role_id_305d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'organization'], name='authenticat_role_id_bf6ece_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'status', 'is_active'], name='authenticat_organiz_1f85f7_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'role', 'status'], name='authenticat_organiz_b80c5d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_active'], name='authenticat_email_7c2cb6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['team', 'organization'], name='authenticat_team_id_2b631e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['login_count', 'organization'], name='authenticat_login_c_7d75ba_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['must_change_password', 'organization'], name='authenticat_must_ch_b1c96d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'last_login', 'organization'], name='authenticat_is_acti_b52e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'status', 'date_joined'], name='authenticat_role_id_6a9e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'sales_target', 'is_active'], name='authenticat_organiz_ea4a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['streak', 'organization', 'role'], name='authenticat_streak_a54910_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization', 'username', 'is_active'], name='authenticat_organiz_20d060_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined', 'organization', 'is_active'], name='authenticat_date_jo_88689a_idx'),
        ),
        migrations.AddIndex(
            model_name='otptoken',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='authenticat_user_id_aac9ae_idx'),
        ),
        migrations.AddIndex(
            model_name='otptoken',
            index=models.Index(fields=['token_hash'], name='authenticat_token_h_d27156_idx'),
        ),
        migrations.AddIndex(
            model_name='otptoken',
            index=models.Index(fields=['expires_at'], name='authenticat_expires_8a3add_idx'),
        ),
        migrations.AddIndex(
            model_name='otptoken',
            index=models.Index(fields=['user', 'created_at'], name='authenticat_user_id_64e106_idx'),
        ),
        migrations.AddIndex(
            model_name='otptoken',
            index=models.Index(fields=['ip_address', 'created_at'], name='authenticat_ip_addr_f72693_idx'),
        ),
        migrations.AddIndex(
            model_name='otptoken',
            index=models.Index(fields=['is_locked', 'locked_until'], name='authenticat_is_lock_f4a0b4_idx'),
        ),
        migrations.AddIndex(
            model_name='otptoken',
            index=models.Index(fields=['user', 'purpose', 'created_at'], name='authenticat_user_id_6f160c_idx'),
        ),
        migrations.AddIndex(
            model_name='otptoken',
            index=models.Index(fields=['attempts', 'max_attempts'], name='authenticat_attempt_4c02f2_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordexpiration',
            index=models.Index(fields=['password_changed_at'], name='authenticat_passwor_b3792e_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordexpiration',
            index=models.Index(fields=['is_expired'], name='authenticat_is_expi_b1577c_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordhistory',
            index=models.Index(fields=['user', 'created_at'], name='authenticat_user_id_9fd5cd_idx'),
        ),
        migrations.AddIndex(
            model_name='secureusersession',
            index=models.Index(fields=['user', 'is_active'], name='authenticat_user_id_1770dc_idx'),
        ),
        migrations.AddIndex(
            model_name='secureusersession',
            index=models.Index(fields=['user', 'created_at'], name='authenticat_user_id_de75bd_idx'),
        ),
        migrations.AddIndex(
            model_name='secureusersession',
            index=models.Index(fields=['session_id'], name='authenticat_session_1546f4_idx'),
        ),
        migrations.AddIndex(
            model_name='secureusersession',
            index=models.Index(fields=['jwt_token_id'], name='authenticat_jwt_tok_d180a6_idx'),
        ),
        migrations.AddIndex(
            model_name='secureusersession',
            index=models.Index(fields=['ip_address', 'created_at'], name='authenticat_ip_addr_2db122_idx'),
        ),
        migrations.AddIndex(
            model_name='secureusersession',
            index=models.Index(fields=['user_agent_hash'], name='authenticat_user_ag_276a05_idx'),
        ),
        migrations.AddIndex(
            model_name='secureusersession',
            index=models.Index(fields=['session_fingerprint'], name='authenticat_session_15b13f_idx'),
        ),
        migrations.AddIndex(
            model_name='secureusersession',
            index=models.Index(fields=['is_suspicious', 'created_at'], name='authenticat_is_susp_2b102a_idx'),
        ),
        migrations.AddIndex(
            model_name='secureusersession',
            index=models.Index(fields=['expires_at'], name='authenticat_expires_cf1d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='secureusersession',
            index=models.Index(fields=['last_activity'], name='authenticat_last_ac_5db268_idx'),
        ),
        migrations.AddIndex(
            model_name='secureusersession',
            index=models.Index(fields=['is_active', 'expires_at'], name='authenticat_is_acti_23402a_idx'),
        ),
        migrations.AddIndex(
            model_name='secureusersession',
            index=models.Index(fields=['login_method', 'created_at'], name='authenticat_login_m_ae8650_idx'),
        ),
        migrations.AddIndex(
            model_name='secureusersession',
            index=models.Index(fields=['device_type', 'created_at'], name='authenticat_device__3a7a01_idx'),
        ),
        migrations.AddIndex(
            model_name='secureusersession',
            index=models.Index(fields=['browser_name', 'created_at'], name='authenticat_browser_79b4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='authenticat_event_t_5d7c80_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['severity', 'timestamp'], name='authenticat_severit_3341e1_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['user', 'timestamp'], name='authenticat_user_id_c988d6_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['ip_address', 'timestamp'], name='authenticat_ip_addr_0ecc22_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['risk_score', 'timestamp'], name='authenticat_risk_sc_500a61_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['is_blocked', 'timestamp'], name='authenticat_is_bloc_0a7f3d_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['user_agent_hash', 'timestamp'], name='authenticat_user_ag_50bfd1_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['correlation_id'], name='authenticat_correla_3bef82_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['is_investigated', 'timestamp'], name='authenticat_is_inve_0cde6a_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['investigated_by', 'investigated_at'], name='authenticat_investi_9dca08_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'severity', 'timestamp'], name='authenticat_event_t_0f7330_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['country', 'timestamp'], name='authenticat_country_4b6832_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['session_id', 'timestamp'], name='authenticat_session_96b3ee_idx'),
        ),
    ]
