# Generated by Django 5.2.2 on 2025-07-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyStreakRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("deals_closed", models.IntegerField(default=0)),
                (
                    "total_deal_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("streak_value", models.FloatField(default=0.0)),
                ("streak_updated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
