# Generated by Django 5.2.2 on 2025-07-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Sales_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailystreakrecord",
            name="streak_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="dailystreakrecord",
            name="total_deal_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
