# Generated by Django 4.2.23 on 2025-07-09 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Sales_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailystreakrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="streak_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailystreakrecord",
            unique_together={("user", "date")},
        ),
    ]
