# Generated by Django 4.2.23 on 2025-07-09 04:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?\\d{10,15}$", "Enter a valid phone number."
                            )
                        ],
                    ),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "satisfaction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("neutral", "Neutral"),
                            ("satisfied", "Satisfied"),
                            ("unsatisfied", "Un-Satisfied"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending"),
                            ("bad_debt", "Bad Debt"),
                            ("clear", "Clear"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="organization.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["client_name"],
                "permissions": [
                    ("view_all_clients", "Can view all clients"),
                    ("view_own_clients", "Can view own clients"),
                    ("create_new_client", "Can create a new client"),
                    ("edit_client_details", "Can edit client details"),
                    ("remove_client", "Can delete a client"),
                ],
                "unique_together": {("email", "organization")},
            },
        ),
    ]
