# Generated by Django 5.2.2 on 2025-06-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_client_delete_clients"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name="client",
            unique_together={("email", "organization")},
        ),
    ]
