# Generated by Django 5.2.2 on 2025-07-03 07:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0003_alter_client_email_alter_client_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?\\d{10,15}$", "Enter a valid phone number."
                    )
                ],
            ),
        ),
    ]
