# Generated by Django 5.2.2 on 2025-07-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "clients",
            "0003_client_active_date_client_address_client_avatar_url_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="satisfaction",
            field=models.CharField(
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("average", "Average"),
                    ("poor", "Poor"),
                    ("positive", "Positive"),
                    ("neutral", "Neutral"),
                    ("negative", "Negative"),
                ],
                default="average",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("prospect", "Prospect"),
                    ("clear", "Clear"),
                    ("pending", "Pending"),
                    ("bad-depth", "Bad Depth"),
                ],
                default="prospect",
                max_length=20,
            ),
        ),
    ]
