# Generated by Django 5.2.2 on 2025-07-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0004_alter_client_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.CharField(max_length=20),
        ),
    ]
