# Generated by Django 5.2.2 on 2025-07-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_alter_client_satisfaction_alter_client_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="satisfaction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("average", "Average"),
                    ("poor", "Poor"),
                    ("positive", "Positive"),
                    ("neutral", "Neutral"),
                    ("negative", "Negative"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("prospect", "Prospect"),
                    ("clear", "Clear"),
                    ("pending", "Pending"),
                    ("bad-depth", "Bad Depth"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
