# Generated by Django 5.2.2 on 2025-07-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_alter_client_satisfaction_alter_client_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("clear", "Clear"),
                    ("pending", "Pending"),
                    ("bad_debt", "Bad Debt"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("prospect", "Prospect"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
