# Generated by Django 5.2.2 on 2025-08-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'permissions': [('view_payment_verification_dashboard', 'Can view payment verification dashboard'), ('view_payment_analytics', 'Can view payment analytics'), ('view_audit_logs', 'Can view audit logs')],
            },
        ),
    ]
