# Generated by Django 5.2.2 on 2025-08-18 04:41

import apps.deals.atomic_operations
import apps.deals.financial_optimizer
import core.security.file_security
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('organization', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('deal_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('payment_status', models.CharField(choices=[('initial payment', 'Initial Payment'), ('partial_payment', 'Partial Payment'), ('full_payment', 'Full Payment')], max_length=50)),
                ('source_type', models.CharField(choices=[('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('google', 'Google'), ('referral', 'Referral'), ('others', 'Others')], max_length=50)),
                ('deal_name', models.CharField(default='', max_length=255)),
                ('deal_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('deal_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('wallet', 'Mobile Wallet'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('cash', 'Cash')], max_length=100)),
                ('deal_remarks', models.TextField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=100)),
                ('client_status', models.CharField(choices=[('pending', 'Pending'), ('loyal', 'Loyal'), ('bad_debt', 'Bad Debt')], default='pending', max_length=100)),
                ('version', models.CharField(choices=[('original', 'Original'), ('edited', 'Edited')], default='original', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_count', models.IntegerField(default=0, help_text='Number of payments made for this deal')),
                ('lock_version', models.PositiveIntegerField(default=1, help_text='Version number for optimistic locking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_deals', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='organization.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='project.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deals_deal',
                'ordering': ['-created_at'],
                'permissions': [('manage_invoices', 'Can manage invoices'), ('access_verification_queue', 'Can access verification queue'), ('verify_deal_payment', 'Can verify deal payments'), ('manage_refunds', 'Can manage refunds'), ('verify_payments', 'Can verify payments')],
            },
            bases=(apps.deals.financial_optimizer.FinancialValidationMixin, apps.deals.atomic_operations.OptimisticLockingMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, help_text="Action performed (e.g., 'created', 'updated', 'verified')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the action')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, help_text='Legacy message field')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Legacy timestamp field')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='deals.deal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('payment_date', models.DateField()),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/', validators=[core.security.file_security.validate_file_security_enhanced])),
                ('payment_remarks', models.TextField(blank=True, null=True)),
                ('received_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_type', models.CharField(choices=[('wallet', 'Mobile Wallet'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('cash', 'Cash')], max_length=50)),
                ('payment_category', models.CharField(choices=[('advance', 'Advance Payment'), ('partial', 'Partial Payment'), ('final', 'Final Payment')], default='partial', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('version', models.PositiveIntegerField(default=1, help_text='Payment version for tracking changes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='deals.deal')),
            ],
            options={
                'db_table': 'deals_payment',
                'ordering': ['-payment_date'],
                'permissions': [('create_deal_payment', 'Can create deal payment')],
            },
            bases=(apps.deals.financial_optimizer.FinancialValidationMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(blank=True, max_length=255, unique=True)),
                ('invoice_number', models.CharField(blank=True, help_text='Human-readable invoice number', max_length=255)),
                ('invoice_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Invoice amount', max_digits=15)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('invoice_status', models.CharField(default='pending', max_length=20)),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='receipts/', validators=[core.security.file_security.validate_file_security_enhanced])),
                ('invoice_file', models.FileField(blank=True, help_text='Invoice document file', null=True, upload_to='invoices/', validators=[core.security.file_security.validate_file_security_enhanced])),
                ('invoice_remarks', models.TextField(blank=True, help_text='Additional remarks for the invoice', null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='deals.deal')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='deals.payment')),
            ],
            options={
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/', validators=[core.security.file_security.validate_file_security_enhanced])),
                ('approval_date', models.DateField(auto_now_add=True)),
                ('verifier_remarks', models.TextField(blank=True, null=True)),
                ('approval_remarks', models.TextField(blank=True, help_text='General approval remarks', null=True)),
                ('failure_remarks', models.CharField(blank=True, choices=[('insufficient_funds', 'Insufficient Funds'), ('bank_decline', 'Bank Decline'), ('technical_error', 'Technical Error'), ('cheque_bounce', 'Cheque Bounce'), ('payment_received_not_reflected', 'Payment Received but not Reflected')], max_length=50, null=True)),
                ('invoice_status', models.CharField(default='pending', help_text='Status of the related invoice', max_length=20)),
                ('amount_in_invoice', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_approvals', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='deals.deal')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='deals.payment')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='deals.paymentinvoice')),
            ],
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['client', 'created_at'], name='deals_deal_client__ea8c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['created_by', 'deal_date'], name='deals_deal_created_90cc76_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['payment_status', 'verification_status'], name='deals_deal_payment_7ed096_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['due_date'], name='deals_deal_due_dat_e9fed1_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['deal_value'], name='deals_deal_deal_va_6beb9c_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'verification_status'], name='deals_deal_organiz_34fafc_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'payment_status'], name='deals_deal_organiz_f86d09_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['source_type'], name='deals_deal_source__b59f34_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'deal_date'], name='deals_deal_organiz_ab09d2_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'created_by'], name='deals_deal_organiz_cdfde6_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'verification_status', 'payment_status'], name='deals_deal_organiz_4be6b6_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'verification_status', 'created_at'], name='deals_deal_organiz_f2913e_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'payment_status', 'created_at'], name='deals_deal_organiz_68b86d_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'deal_date', 'verification_status'], name='deals_deal_organiz_2a1ddf_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'deal_value', 'verification_status'], name='deals_deal_organiz_0966aa_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'created_at', 'deal_value'], name='deals_deal_organiz_508457_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'source_type', 'created_at'], name='deals_deal_organiz_c47a2a_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'client_status', 'verification_status'], name='deals_deal_organiz_bce80f_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['organization', 'payment_method', 'payment_status'], name='deals_deal_organiz_d63623_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['created_at', 'verification_status'], name='deals_deal_created_1e8bda_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['deal_date', 'payment_status'], name='deals_deal_deal_da_0375ca_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['due_date', 'payment_status'], name='deals_deal_due_dat_75ec44_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['updated_at', 'organization'], name='deals_deal_updated_18626c_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['deal_value', 'organization'], name='deals_deal_deal_va_cc8846_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['payment_count', 'organization'], name='deals_deal_payment_46f778_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['currency', 'organization'], name='deals_deal_currenc_1290b3_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['created_by', 'organization', 'created_at'], name='deals_deal_created_ee7b84_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['updated_by', 'organization', 'updated_at'], name='deals_deal_updated_3d1b15_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['client', 'verification_status', 'payment_status'], name='deals_deal_client__e3b36f_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['client', 'deal_value', 'created_at'], name='deals_deal_client__2e8c75_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['project', 'organization', 'verification_status'], name='deals_deal_project_69947d_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['version', 'organization', 'updated_at'], name='deals_deal_version_d30115_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['client_status', 'organization', 'created_at'], name='deals_deal_client__fcdb30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deal',
            unique_together={('organization', 'deal_id')},
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['deal', '-created_at'], name='deals_activ_deal_id_34c2c8_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', '-created_at'], name='deals_activ_action_6a31fa_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-created_at'], name='deals_activ_user_id_b86820_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['deal', 'payment_date'], name='deals_payme_deal_id_73d309_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='deals_payme_created_bc0ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['received_amount'], name='deals_payme_receive_947fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['deal', 'payment_category', 'payment_date'], name='deals_payme_deal_id_ab5e25_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['deal', 'payment_type', 'created_at'], name='deals_payme_deal_id_d9927d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['deal', 'received_amount', 'payment_date'], name='deals_payme_deal_id_b0a000_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date', 'received_amount'], name='deals_payme_payment_08703e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type', 'payment_date'], name='deals_payme_payment_c678b1_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_category', 'created_at'], name='deals_payme_payment_e55195_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['transaction_id'], name='deals_payme_transac_f573ee_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['cheque_number'], name='deals_payme_cheque__2bf47d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at', 'received_amount'], name='deals_payme_created_01c435_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['updated_at', 'deal'], name='deals_payme_updated_0b5a9d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['deal', 'created_at', 'received_amount'], name='deals_payme_deal_id_ce83cf_idx'),
        ),
    ]
