# Generated by Django 5.2.2 on 2025-08-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentapproval',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('requires_info', 'Requires Additional Information')], default='pending', help_text='Approval status from verifier', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentapproval',
            name='verified_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount verified by the verifier', max_digits=15, null=True),
        ),
    ]
