# Generated by Django 5.2.2 on 2025-06-27 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams",
                to="organization.organization",
            ),
        ),
    ]
